import Link from "next/link";
import { Scale, ArrowLeft, AlertTriangle } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen">
      <header className="border-b">
        <div className="max-w-4xl mx-auto px-4 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <Scale className="h-6 w-6 text-primary" />
            <span className="font-bold">NyayaSetu</span>
          </Link>
          <Link href="/"><Button variant="ghost" size="sm"><ArrowLeft className="h-4 w-4 mr-1" /> Back</Button></Link>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 py-12 prose prose-neutral max-w-none">
        <div className="flex items-center gap-3 mb-6">
          <AlertTriangle className="h-8 w-8 text-orange-500" />
          <h1 className="text-3xl font-bold">Disclaimer — अस्वीकरण</h1>
        </div>

        <div className="bg-orange-50 border border-orange-200 rounded-lg p-6 mb-8">
          <p className="font-semibold text-orange-800 mb-2">Important Notice — महत्वपूर्ण सूचना</p>
          <p className="text-orange-700 text-sm">
            NyayaSetu is an AI-powered legal information tool. It is NOT a law firm, does NOT provide
            legal advice, and does NOT create an attorney-client relationship. AI-generated content
            may contain errors or inaccuracies.
          </p>
          <p className="text-orange-700 text-sm mt-2">
            NyayaSetu एक AI-संचालित कानूनी सूचना उपकरण है। यह कोई कानूनी फर्म नहीं है, कानूनी
            सलाह प्रदान नहीं करता, और वकील-मुवक्किल संबंध नहीं बनाता। AI-जनित सामग्री में त्रुटियां हो सकती हैं।
          </p>
        </div>

        <h2 className="text-xl font-semibold mt-8 mb-3">1. No Legal Advice</h2>
        <p className="text-muted-foreground mb-4">
          The information provided by NyayaSetu — including contract analyses, legal notice drafts,
          GST playbooks, and credit recovery plans — is generated by artificial intelligence for
          informational purposes only. This information should not be construed as legal advice.
          For specific legal matters, always consult a qualified advocate enrolled with the Bar
          Council of India.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">2. AI Limitations</h2>
        <p className="text-muted-foreground mb-4">
          Our AI models are trained on publicly available legal information but may not reflect the
          most recent amendments, court rulings, or regulatory changes. AI-generated content may
          contain inaccuracies, omissions, or errors. Users must independently verify all
          information before acting upon it.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">3. No Guarantee of Outcomes</h2>
        <p className="text-muted-foreground mb-4">
          Using NyayaSetu does not guarantee any particular legal outcome. The effectiveness of
          legal notices, recovery strategies, or dispute responses depends on many factors beyond
          the scope of this Service.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">4. Document Accuracy</h2>
        <p className="text-muted-foreground mb-4">
          Legal notices and documents generated by NyayaSetu are AI-drafted templates. Before sending
          any legal notice or filing any document, we strongly recommend having it reviewed by a
          qualified legal professional to ensure accuracy, completeness, and compliance with
          applicable laws.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">5. Jurisdiction</h2>
        <p className="text-muted-foreground mb-4">
          NyayaSetu&apos;s AI is trained primarily on Indian law (Indian Contract Act, GST Act, SARFAESI Act,
          NI Act, MSME Development Act, etc.). It may not be suitable for legal matters governed
          by the laws of other jurisdictions.
        </p>

        <p className="text-sm text-muted-foreground mt-8 border-t pt-6">
          By using NyayaSetu, you acknowledge that you have read, understood, and agree to this
          Disclaimer. If you have questions, contact us at <strong>legal@nyayasetu.in</strong>.
        </p>
      </main>
    </div>
  );
}
